# Generated by Django 2.1.5 on 2019-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_scraper', '0002_auto_20190210_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category_turkish',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
