# Generated by Django 2.2.1 on 2019-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_scraper', '0004_auto_20190519_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PffReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=256)),
                ('month', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
