# Generated by Django 2.2.1 on 2019-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_scraper', '0005_pffreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pffreport',
            name='file',
        ),
        migrations.AddField(
            model_name='pffreport',
            name='file_url',
            field=models.URLField(default='http://media4.jetbim.com/public/uploads/reports_8494932.docx'),
            preserve_default=False,
        ),
    ]
