# Generated by Django 2.2.1 on 2019-05-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_scraper', '0006_auto_20190519_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='article2',
            name='related_pff_report',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='newspaper_scraper.PffReport'),
            preserve_default=False,
        ),
    ]
